
name: 'airbnb_analytics_core'
version: '2.0.0'
profile: 'airbnb_prod'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  airbnb_analytics_core:
    # Staging: Light transformations, casting, renaming.
    staging:
      +materialized: view
      +schema: staging
    
    # Intermediate: Complex joins and business logic preparation.
    intermediate:
      +materialized: ephemeral

    # Marts: Final consumption layer.
    marts:
      +materialized: table
      +schema: marts
      +post-hook:
        - "GRANT SELECT ON {{ this }} TO ROLE REPORTER"
      
      core:
        fct_reviews:
          +materialized: incremental
          +unique_key: review_id
          +on_schema_change: "append_new_columns"
